### ISSUE TITLE
Board design questions

### ISSUE THREAD

**Issue by wifixcort** [ElectronicCats/DAP-Cat-Programmer#1]
Hi.

I have 3 questions about your board design:

1. Why do you use 2 F.Cu and 2 B.Cu Zone outlines instead of just use one for each side?
2.There is a espetial reason for use 0.508 clearance instead a smaller one
3.You make a big loop on 5V or A4 pin in the USB connector, is that really needed, because fisically is the same pin, I think it's not necesary, or I'm wrong?

If you change the rotation of some components it turn out a simplier PCB routing

**Comment by sabas1080** [comment]
Hi @wifixcort 

1.- An error when designing does not affect anything but we will remove
2.- It is just the design standard we use
3.- double connection is necessary for USB-C

Welcome to contribute if you consider the design can be improved, we look forward to your pullrequest

**Comment by wifixcort** [comment]
Could you create a branch named : "develop"

**Comment by sabas1080** [comment]
@wifixcort ok for me, send me pullrequest when ready, thanks :D

**Comment by sabas1080** [comment]
solution #2
