### ISSUE TITLE
What's DAP_TransferAbort for?

### ISSUE THREAD

**Issue by llinjupt** [ElectronicCats/DAP-Cat-Programmer#3]
Hi Mr. Cat,

First thanks for your great work. I have found a variable named DAP_TransferAbort which is not set as 1 forever. It seems the porting work has left out something there.

**Comment by wero1414** [comment]
is it giving you problems at compile? or what do you mean?

Thanks for the feedback!

**Comment by llinjupt** [comment]
No, not yet. I just want to know what the varialbe DAP_TransferAbort  is for and Why should it exist if no where it is set  to 1 which means it doesn't take any work? I have checked the orignial DAPLink code and found the answer there. Thanks.
