### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by elfmimi** [ElectronicCats/DAP-Cat-Programmer#4]
README.md says,
> Firmware released under an GNU AGPL v3.0 license. See the LICENSE file for more information.

[The image](https://raw.githubusercontent.com/ElectronicCats/AjoloteBoard/master/OpenSourceLicense.png) says,
> Software GPL-3.0-or-later

And the LICENSE file says,
> GNU LESSER GENERAL PUBLIC LICENSE Version 2.1

Which is correct?

I believe in this case as ARM originating source files are licensed under Apache-2.0, rest of the firmware code ought to be LGPL .

Could you clarify this and fix the document? (I suppose the image can be just removed.)

**Comment by sabas1080** [comment]
corrected, thanks for your notes @elfmimi

**Comment by elfmimi** [comment]
Thank you for your quick action. @sabas1080 

There is still this line. and it is still confusing.
> Firmware released under an GNU **AGPL** v3.0 license. See the LICENSE file for more information.

**Comment by sabas1080** [comment]
corrected
