### ISSUE TITLE
DAPCat not recognized as a CMSIS-DAP device

### ISSUE THREAD

**Issue by Daniel9719** [ElectronicCats/DAP-Cat-Programmer#7]
**Describe the problem:**
I've bought the DAPCat and tried to make it run under OpenOCD using the cmsis-dap interface but the device does not seem to be recognized as a CMSIS DAP device.

I tried to contact the support team of Electronic Cats ([support1@electroniccats.com](mailto:support1@electroniccats.com)) back on October 5th, 2022 with the subject "DapCat" under my email ([danieldraftsman@gmail.com](mailto:danieldraftsman@gmail.com)) but I didn't get a solution to this problem. I was instructed to reflash my device using the release file CMSIS_DAP.ino.ch552.hex found at  https://github.com/ElectronicCats/DAP-Cat-Programmer/releases using the WCHISPTool and by setting the device on boot mode (which I accomplished by pressing the boot button on the board while I powered on the device). I was successful at flashing the file into the board as you can see below

![image](https://github.com/ElectronicCats/DAP-Cat-Programmer/assets/56694707/fbb4856c-472b-4409-8e77-ae938515013e)

But even after following those steps I haven't been able to have the device recognized as a CMSIS-DAP device.

**Reproduce steps**
First, have the device recognized by the linux environment, you can use the command `lsusb` for this purpose as illustrated below

![image](https://github.com/ElectronicCats/DAP-Cat-Programmer/assets/56694707/b2193fe0-2be3-4f29-b18a-1d8f4ee0856a)

Run the following command under a linux environment (I've specified my environment below)
`sudo openocd -c "gdb_port 50000" -c "tcl_port 50001" -c "telnet_port 50002" -s /home/danielortiz2/OS_Course_Skills/os_core_skills_course -c "debug_level 4" -f /home/vscode/.vscode-server/extensions/marus25.cortex-debug-1.12.1/support/openocd-helpers.tcl -f /interface/cmsis-dap.cfg -c "transport select swd" -f /target/stm32f4x.cfg `

**Expected behavior:**
I'd expect the DAPCat to be recognized as a CMSIS-DAP device

**Screenshots:**
The result that I get from OpenOCD after running the previous  command is the following:

> Open On-Chip Debugger 0.11.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
User : 16 3 options.c:63 configuration_output_handler(): debug_level: 4
User : 17 3 options.c:63 configuration_output_handler(): 
Debug: 18 3 configuration.c:97 find_file(): found /home/vscode/.vscode-server/extensions/marus25.cortex-debug-1.12.1/support/openocd-helpers.tcl
User : 19 3 options.c:63 configuration_output_handler(): CDLiveWatchSetupUser : 20 3 options.c:63 configuration_output_handler(): 
Debug: 21 3 configuration.c:97 find_file(): found /usr/bin/../share/openocd/scripts//interface/cmsis-dap.cfg
Debug: 22 4 command.c:146 script_debug(): command - adapter driver cmsis-dap
Debug: 24 4 command.c:146 script_debug(): command - transport select swd
User : 25 4 options.c:63 configuration_output_handler(): swdUser : 26 4 options.c:63 configuration_output_handler(): 
Debug: 27 4 configuration.c:97 find_file(): found /usr/bin/../share/openocd/scripts//target/stm32f4x.cfg
Debug: 28 4 configuration.c:97 find_file(): found /usr/bin/../share/openocd/scripts/target/swj-dp.tcl
Debug: 29 4 command.c:146 script_debug(): command - transport select
Debug: 30 4 configuration.c:97 find_file(): found /usr/bin/../share/openocd/scripts/mem_helper.tcl
Debug: 31 4 command.c:146 script_debug(): command - add_usage_text mrw address
Debug: 33 4 command.c:1115 help_add_command(): added 'mrw' help text
Debug: 34 5 command.c:146 script_debug(): command - add_help_text mrw Returns value of word in memory.
Debug: 36 5 command.c:1128 help_add_command(): added 'mrw' help text
Debug: 37 5 command.c:146 script_debug(): command - add_usage_text mrh address
Debug: 39 5 command.c:1115 help_add_command(): added 'mrh' help text
Debug: 40 5 command.c:146 script_debug(): command - add_help_text mrh Returns value of halfword in memory.
Debug: 42 5 command.c:1128 help_add_command(): added 'mrh' help text
Debug: 43 5 command.c:146 script_debug(): command - add_usage_text mrb address
Debug: 45 5 command.c:1115 help_add_command(): added 'mrb' help text
Debug: 46 5 command.c:146 script_debug(): command - add_help_text mrb Returns value of byte in memory.
Debug: 48 5 command.c:1128 help_add_command(): added 'mrb' help text
Debug: 49 5 command.c:146 script_debug(): command - add_usage_text mmw address setbits clearbits
Debug: 51 5 command.c:1115 help_add_command(): added 'mmw' help text
Debug: 52 5 command.c:146 script_debug(): command - add_help_text mmw Modify word in memory. new_val = (old_val & ~clearbits) | setbits;
Debug: 54 5 command.c:1128 help_add_command(): added 'mmw' help text
Debug: 55 5 command.c:146 script_debug(): command - transport select
Debug: 56 5 command.c:146 script_debug(): command - transport select
Debug: 57 5 command.c:146 script_debug(): command - transport select
Debug: 58 5 command.c:146 script_debug(): command - swd newdap stm32f4x cpu -irlen 4 -ircapture 0x1 -irmask 0xf -expected-id 0x2ba01477
Debug: 59 5 tcl.c:571 jim_newtap_cmd(): Creating New Tap, Chip: stm32f4x, Tap: cpu, Dotted: stm32f4x.cpu, 8 params
Debug: 60 5 core.c:1484 jtag_tap_init(): Created Tap: stm32f4x.cpu @ abs position 0, irlen 0, capture: 0x0 mask: 0x0
Debug: 61 5 command.c:146 script_debug(): command - dap create stm32f4x.dap -chain-position stm32f4x.cpu
Debug: 62 5 command.c:146 script_debug(): command - transport select
Debug: 63 5 command.c:146 script_debug(): command - target create stm32f4x.cpu cortex_m -endian little -dap stm32f4x.dap
Debug: 64 5 command.c:375 register_command(): command 'rtt' is already registered in '<global>' context
Debug: 65 5 command.c:146 script_debug(): command - stm32f4x.cpu configure -work-area-phys 0x20000000 -work-area-size 0x8000 -work-area-backup 0
Debug: 66 5 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas
Debug: 67 5 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas
Debug: 68 5 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas
Debug: 69 5 command.c:146 script_debug(): command - flash bank stm32f4x.flash stm32f2x 0 0 0 0 stm32f4x.cpu
Debug: 71 6 tcl.c:1319 handle_flash_bank_command(): 'stm32f2x' driver usage field missing
Debug: 72 6 command.c:146 script_debug(): command - flash bank stm32f4x.otp stm32f2x 0x1fff7800 0 0 0 stm32f4x.cpu
Debug: 74 6 command.c:375 register_command(): command 'stm32f2x' is already registered in '<global>' context
Debug: 75 6 command.c:375 register_command(): command 'lock' is already registered in 'stm32f2x' context
Debug: 76 6 command.c:375 register_command(): command 'unlock' is already registered in 'stm32f2x' context
Debug: 77 6 command.c:375 register_command(): command 'mass_erase' is already registered in 'stm32f2x' context
Debug: 78 6 command.c:375 register_command(): command 'options_read' is already registered in 'stm32f2x' context
Debug: 79 6 command.c:375 register_command(): command 'options_write' is already registered in 'stm32f2x' context
Debug: 80 6 command.c:375 register_command(): command 'optcr2_write' is already registered in 'stm32f2x' context
Debug: 81 6 command.c:375 register_command(): command 'otp' is already registered in 'stm32f2x' context
Debug: 82 6 tcl.c:1319 handle_flash_bank_command(): 'stm32f2x' driver usage field missing
Debug: 83 6 command.c:146 script_debug(): command - adapter speed 2000
Debug: 85 6 core.c:1822 jtag_config_khz(): handle jtag khz
Debug: 86 6 core.c:1785 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 87 6 core.c:1785 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 88 6 command.c:146 script_debug(): command - adapter srst delay 100
Debug: 90 6 command.c:146 script_debug(): command - transport select
Debug: 91 6 command.c:146 script_debug(): command - reset_config srst_nogate
Debug: 93 6 command.c:146 script_debug(): command - transport select
Debug: 94 6 command.c:146 script_debug(): command - cortex_m reset_config sysresetreq
Debug: 96 6 command.c:146 script_debug(): command - stm32f4x.cpu configure -event examine-end 
        # Enable debug during low power modes (uses more power)
        # DBGMCU_CR |= DBG_STANDBY | DBG_STOP | DBG_SLEEP
        mmw 0xE0042004 0x00000007 0
        # Stop watchdog counters during halt
        # DBGMCU_APB1_FZ |= DBG_IWDG_STOP | DBG_WWDG_STOP
        mmw 0xE0042008 0x00001800 0
Debug: 97 6 command.c:146 script_debug(): command - stm32f4x.cpu configure -event trace-config 
        # Set TRACE_IOEN; TRACE_MODE is set to async; when using sync
        # change this value accordingly to configure trace pins
        # assignment
        mmw 0xE0042004 0x00000020 0
Debug: 98 6 command.c:146 script_debug(): command - stm32f4x.cpu configure -event reset-init 
        # Configure PLL to boost clock to HSI x 4 (64 MHz)
        mww 0x40023804 0x08012008   ;# RCC_PLLCFGR 16 Mhz /8 (M) * 128 (N) /4(P)
        mww 0x40023C00 0x00000102   ;# FLASH_ACR = PRFTBE | 2(Latency)
        mmw 0x40023800 0x01000000 0 ;# RCC_CR |= PLLON
        sleep 10                    ;# Wait for PLL to lock
        mmw 0x40023808 0x00001000 0 ;# RCC_CFGR |= RCC_CFGR_PPRE1_DIV2
        mmw 0x40023808 0x00000002 0 ;# RCC_CFGR |= RCC_CFGR_SW_PLL
        # Boost JTAG frequency
        adapter speed 8000
Debug: 99 6 command.c:146 script_debug(): command - stm32f4x.cpu configure -event reset-start 
        # Reduce speed since CPU speed will slow down to 16MHz with the reset
        adapter speed 2000
Info : 100 6 server.c:311 add_service(): Listening on port 50001 for tcl connections
Info : 101 6 server.c:311 add_service(): Listening on port 50002 for telnet connections
Debug: 102 6 command.c:146 script_debug(): command - init
Debug: 104 6 command.c:146 script_debug(): command - target init
Debug: 106 6 command.c:146 script_debug(): command - target names
Debug: 107 6 command.c:146 script_debug(): command - stm32f4x.cpu cget -event gdb-flash-erase-start
Debug: 108 6 command.c:146 script_debug(): command - stm32f4x.cpu configure -event gdb-flash-erase-start reset init
Debug: 109 6 command.c:146 script_debug(): command - stm32f4x.cpu cget -event gdb-flash-write-end
Debug: 110 6 command.c:146 script_debug(): command - stm32f4x.cpu configure -event gdb-flash-write-end reset halt
Debug: 111 6 command.c:146 script_debug(): command - stm32f4x.cpu cget -event gdb-attach
Debug: 112 6 command.c:146 script_debug(): command - stm32f4x.cpu configure -event gdb-attach halt 1000
Debug: 113 6 target.c:1639 handle_target_init_command(): Initializing targets...
Debug: 114 6 semihosting_common.c:99 semihosting_common_init():  
Debug: 115 7 cmsis_dap_usb_bulk.c:176 cmsis_dap_usb_open(): enumerating interfaces of 0x1d6b:0x0003
Debug: 116 9 cmsis_dap_usb_bulk.c:156 cmsis_dap_usb_open(): found product string of 0x1209:0xc550 'CMSIS-DAP'
**Debug: 117 9 cmsis_dap_usb_bulk.c:176 cmsis_dap_usb_open(): enumerating interfaces of 0x1209:0xc550
Debug: 118 9 cmsis_dap_usb_bulk.c:243 cmsis_dap_usb_open(): skipping interface 0, endpoint[0] is not bulk out**
Debug: 119 9 cmsis_dap_usb_bulk.c:176 cmsis_dap_usb_open(): enumerating interfaces of 0x1d6b:0x0002
Error: 120 10 cmsis_dap_usb_hid.c:139 cmsis_dap_hid_open(): unable to open CMSIS-DAP device 0x1209:0xc550
Error: 121 10 cmsis_dap.c:259 cmsis_dap_open(): unable to find a matching CMSIS-DAP device
Debug: 122 10 command.c:628 run_command(): Command 'init' failed with error code -4
User : 123 10 command.c:694 command_run_line(): 
Debug: 124 10 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas

The issue lies in lines 

> Debug: 117 9 cmsis_dap_usb_bulk.c:176 cmsis_dap_usb_open(): enumerating interfaces of 0x1209:0xc550
Debug: 118 9 cmsis_dap_usb_bulk.c:243 cmsis_dap_usb_open(): skipping interface 0, endpoint[0] is not bulk out

where it seems like the DAPCat does not support bulk transfers as specified by the cmsis_dap_usb_bulk.c file at https://sourceforge.net/p/openocd/code/ci/master/tree/src/jtag/drivers/cmsis_dap_usb_bulk.c#l256

If applicable, add screenshots or photos to help explain your problem.

**My environment**
I'm running the command under a docker container with Ubuntu 22.04 as the OS
I've opened the container through WSL2 version 2.2.4.0 on VSCode version 1.90.2

**Possible solution**
The issue might lie on checking whether the device is configured properly to support bulk transfers.

**Comment by Eric286** [comment]
Hello @Daniel9719,

Based on the logs, it appears the issue might be with the bulk endpoint not being available. Check the USB descriptors using lsusb -v to see if the bulk endpoints are correctly listed.

lsusb -v -d 1209:c550

Also, ensure that the DAPCat device is properly enumerated by the USB subsystem. You can use dmesg and lsusb to verify that the device is recognized correctly:

dmesg | grep -i usb
lsusb


Please send me the output of the lsusb -v command and the message that appears from the dmesg command.

Have a nice day!

Support Team.

**Comment by Eric286** [comment]
Hello @Daniel9719,

Due to lack of response we will close this issue now, however, please feel free to reach out to us again in case you have further suggestions, encounter an issue, or you would like to contribute.

Have a nice day!

Support Team.

**Comment by Daniel9719** [comment]
Hi Eric,Sorry for not replying but Im in a business trip and don’t have access to my DAPCat right now, Ill take a look into it once I get back home but that will be until next Saturday 20 July.

**Comment by Eric286** [comment]
Good day @Daniel9719 ,

Do you like more time or do you prefer to close the issue?

Have a nice day!

**Comment by Daniel9719** [comment]
Hi , Im gonna address it this Friday, sorry for the delay, its been a pretty busy week at work :sEl 24 jul 2024, a la(s) 12:34 p.m., Eric Chavez ***@***.***> escribió:﻿
Good day @Daniel9719 ,
Do you like more time or do you prefer to close the issue?
Have a nice day!

**Comment by Eric286** [comment]
Hello @Daniel9719 

Don't worry, I'm waiting for your response then, if you think you need more time please let me know, or if you have any other questions, don't hesitate to tell us.

Have a nice Day!

**Comment by Daniel9719** [comment]
Hi Eric, I found some time to get what you asked.
After running the command  `lsusb -v -d 1209:c550` I get this response

> Bus 001 Device 004: ID 1209:c550 Generic CMSIS-DAP
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x1209 Generic
  idProduct          0xc550 
  bcdDevice            1.00
  iManufacturer           1 ElectronicCats
  iProduct                2 CMSIS-DAP
  iSerial                 3 CH55x
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              200mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      29
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          **Transfer Type            Interrupt**
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          **Transfer Type            Interrupt**
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
cannot read device status, Resource temporarily unavailable (11)

I'm not an expert on USB to be honest but **I don't see any Bulk tranfer types on the endpoints descriptors**, but rather interrupt types which is what OpenOCD was complaining about.

After running the command  `lsusb` I get the following answer which asures me that the device is recognized by the system

> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
**Bus 001 Device 005: ID 1209:c550 Generic CMSIS-DAP**
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

And after running the command `dmesg | grep -i usb` to check if  the DAPCat device is properly enumerated by the USB subsystem, I get the following answer which at the end I guess it does recognize the device correctly:

> [    0.103818] ACPI: bus type USB registered
[    0.103827] usbcore: registered new interface driver usbfs
[    0.103832] usbcore: registered new interface driver hub
[    0.103840] usbcore: registered new device driver usb
[    0.175478] usbcore: registered new interface driver cdc_ether
[    0.175981] usbcore: registered new interface driver cdc_ncm
[    0.176475] usbcore: registered new interface driver r8153_ecm
[    0.177663] usbcore: registered new interface driver cdc_acm
[    0.177987] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[    0.178429] vhci_hcd vhci_hcd.0: USB/IP Virtual Host Controller
[    0.178671] vhci_hcd vhci_hcd.0: new USB bus registered, assigned bus number 1
[    0.179197] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.15
[    0.179533] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.179906] usb usb1: Product: USB/IP Virtual Host Controller
[    0.180261] usb usb1: Manufacturer: Linux 5.15.153.1-microsoft-standard-WSL2 vhci_hcd
[    0.180667] usb usb1: SerialNumber: vhci_hcd.0
[    0.181131] hub 1-0:1.0: USB hub found
[    0.181815] vhci_hcd vhci_hcd.0: USB/IP Virtual Host Controller
[    0.182118] vhci_hcd vhci_hcd.0: new USB bus registered, assigned bus number 2
[    0.182518] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    0.182917] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.15
[    0.183184] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.183435] usb usb2: Product: USB/IP Virtual Host Controller
[    0.183643] usb usb2: Manufacturer: Linux 5.15.153.1-microsoft-standard-WSL2 vhci_hcd
[    0.183906] usb usb2: SerialNumber: vhci_hcd.0
[    0.184218] hub 2-0:1.0: USB hub found
[    0.188657] usbcore: registered new interface driver usbhid
[    0.188909] usbhid: USB HID core driver
[  157.570264] usb 1-1: new high-speed USB device number 2 using vhci_hcd
[  157.720325] usb 1-1: SetAddress Request (2) to port 0
[  157.763631] usb 1-1: New USB device found, idVendor=0483, idProduct=3754, bcdDevice= 1.00
[  157.763635] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  157.763636] usb 1-1: Product: STLINK-V3
[  157.763637] usb 1-1: Manufacturer: STMicroelectronics
[  157.763638] usb 1-1: SerialNumber: 003300493431511937393330
[  157.765751] cdc_acm 1-1:1.1: ttyACM0: USB ACM device
[  176.525675] usb 1-1: USB disconnect, device number 2
[  497.570437] usb 1-1: new high-speed USB device number 3 using vhci_hcd
[  497.870280] usb 1-1: new full-speed USB device number 4 using vhci_hcd
[  498.020239] usb 1-1: SetAddress Request (4) to port 0
[  498.055801] usb 1-1: New USB device found, idVendor=1209, idProduct=c550, bcdDevice= 1.00
[  498.055804] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  498.055805] usb 1-1: Product: CMSIS-DAP
[  498.055806] usb 1-1: Manufacturer: ElectronicCats
[  498.055806] usb 1-1: SerialNumber: CH55x
[  498.059382] hid-generic 0003:1209:C550.0001: hiddev96,hidraw0: USB HID v1.10 Device [ElectronicCats CMSIS-DAP] on usb-vhci_hcd.0-1/input0
[ 1100.006406] usb 1-1: USB disconnect, device number 4
[ 1110.680367] usb 1-1: new full-speed USB device number 5 using vhci_hcd
[ 1110.830254] usb 1-1: SetAddress Request (5) to port 0
[ 1110.865261] usb 1-1: New USB device found, idVendor=1209, idProduct=c550, bcdDevice= 1.00
[ 1110.865263] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
**[ 1110.865264] usb 1-1: Product: CMSIS-DAP
[ 1110.865265] usb 1-1: Manufacturer: ElectronicCats
[ 1110.865265] usb 1-1: SerialNumber: CH55x
[ 1110.868818] hid-generic 0003:1209:C550.0002: hiddev96,hidraw0: USB HID v1.10 Device [ElectronicCats CMSIS-DAP] on usb-vhci_hcd.0-1/input0**

**Comment by Eric286** [comment]
Hello @Daniel9719 

I'm going to try to replicate the problem to see the fastest option to solve it.

Could you try reflashing the device please, follow the same procedure to flash the device using the WCHISPTool and set the device in boot mode.

Have a nice Day!

**Comment by Eric286** [comment]
Hello @Daniel9719 

Could you tell me how many times you tried to flash the device and if you tried it with another computer?

Have a nice Day!

**Comment by Daniel9719** [comment]
Hi Eric, I've just reflashed the device with the WCHISPTool following the same instructions from my first comment and I still have the same issue. Im using the  CMSIS_DAP.ino.ch552.hex file from the release 1.1 although I zee that you have a new version 1.2 without an  CMSIS_DAP.ino.ch552.hex file on it. Could it be possible to get the  CMSIS_DAP.ino.ch552.hex for that version?
So far I've tried reflashing 5 times and still the same messages. Not sure if I'm missing a step or something, specailly because there's no manual with the right procedures to follow

**Comment by Eric286** [comment]
[hex file.zip](https://github.com/user-attachments/files/16534191/hex.file.zip)

Hello @Daniel9719 

Here I give you the File, if you could record the process when you upload it, if it gives you any errors to verify what else could be happening.

Have a nice Day!

**Comment by Eric286** [comment]
Hello @Daniel9719

Was the file helpful to you?

Did you get a different error?

Have a nice Day!

**Comment by Daniel9719** [comment]
Hi Eric, 

Sorry I don't have a tool to record my screen but I was able to flash the new hex file into the device without any errors but I'm seeing the same error on OpenOCD =/. The only difference I've noticed is the product name being CH55x CMSIS-DAP and having a USB ID 1209:c55d. I've attached the files with the logs I got from OpenOCD, running lsusb and dmseg

[lsusb_Log.txt](https://github.com/user-attachments/files/16620429/lsusb_Log.txt)
[dmesg_Log.txt](https://github.com/user-attachments/files/16620430/dmesg_Log.txt)
[OpenOCD_Log.txt](https://github.com/user-attachments/files/16620431/OpenOCD_Log.txt)

**Comment by Eric286** [comment]
Hi @Daniel9719 

Please flash the first file (CMSIS_DAP.ino.ch552.hex), and a moment before these lines appear:

Debug: 117 9 cmsis_dap_usb_bulk.c:176 cmsis_dap_usb_open(): enumerating interfaces of 0x1209:0xc550
Debug: 118 9 cmsis_dap_usb_bulk.c:243 cmsis_dap_usb_open(): skipping interface 0, endpoint[0] is not bulk out}


press and hold the boot button

![imagen](https://github.com/user-attachments/assets/43988c40-a63a-4c34-a5b0-00072cb7300e)

Could you tell me what version of openocd you have installed?

Also please try the same procedure in Windows please.

Have a nice Day!

**Comment by Eric286** [comment]
Hello @Daniel9719,

Due to lack of response we will close this issue now, however, please feel free to reach out to us again in case you have further suggestions, encounter an issue, or you would like to contribute.

Have a nice day!

Support Team.
